# Generated by Django 4.0.4 on 2022-12-14 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='userName',
        ),
        migrations.AddField(
            model_name='question',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
